language: erlang
script: "./rebar compile && ./rebar skip_deps=true eunit"
otp_release:
- 17.4
# fails to publish SSL information to coveralls (SSL issue in this version)
#- 17.3
- 17.1
- 17.0
- R16B03-1
- R16B03
- R16B02
- R16B01
notifications:
  slack:
    secure: R/DFvrTxdCqOtfQ9Fp9x21Dsd74nltDk98LR8Gq/hydJIR8IC6I62b8XLje74YFb0yjtXc6v3AIrZAu8WuLDn6fij+yGV0nRy4z3pZA2Sq9qN1QEZ2MYpRJWy36ZU4qf/ST3ZcUArIQr7hGslpSEJy7f6PhKajcU/5p97Ps3k2s=
