language: erlang
script: "make compile test"
install: "sudo pip install codecov"
after_success: "codecov"
otp_release:
- 21.3
- 21.2
- 21.1
- 21.0
# fails in math and number conversion:
#- 20.3
- 20.2
- 20.1
- 20.0
- 19.3
- 19.2
- 19.1
- 19.0
- 18.3
- 18.2.1
- 18.2
- 18.1
- 18.0
notifications:
  slack:
    secure: R/DFvrTxdCqOtfQ9Fp9x21Dsd74nltDk98LR8Gq/hydJIR8IC6I62b8XLje74YFb0yjtXc6v3AIrZAu8WuLDn6fij+yGV0nRy4z3pZA2Sq9qN1QEZ2MYpRJWy36ZU4qf/ST3ZcUArIQr7hGslpSEJy7f6PhKajcU/5p97Ps3k2s=
